# Generated by Django 5.2.1 on 2025-06-19 18:05

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activation_token_expiry",
            field=models.DateTimeField(
                default=users.models.default_activation_token_expiry
            ),
        ),
    ]
