# Generated by Django 5.2.1 on 2025-06-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
