# Generated by Django 5.2.6 on 2025-09-12 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendinguser',
            old_name='password',
            new_name='raw_password',
        ),
    ]
