# Generated by Django 5.2.6 on 2025-09-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_password_pendinguser_raw_password'),
    ]

    operations = [
    ]
