# Generated by Django 5.2.6 on 2025-09-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_auto_20250912_1235"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pendinguser",
            old_name="raw_password",
            new_name="password",
        ),
    ]
