services:
  user-service:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - user-db
    environment:
      - DB_HOST=db
      - DB_NAME=user_service_db
      - DB_USER=user_service_user
      - DB_PASSWORD=user_service_password
  user-db:
    image: postgres:14 
    environment:
      - POSTGRES_DB=user_service_db
      - POSTGRES_USER=user_service_user
      - POSTGRES_PASSWORD=user_service_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: