services:
  user-service:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - user-db
      - rabbitmq
  user-db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=user_service_db
      - POSTGRES_USER=user_service_user
      - POSTGRES_PASSWORD=user_service_password

  rabbitmq:
    image: rabbitmq:3
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


  celery-beat:
    build: .
    command: celery -A user_service beat --loglevel=INFO
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - user-service
      - rabbitmq

  celery-worker:
    build: .
    command: celery -A user_service worker --loglevel=INFO
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - user-service
      - rabbitmq
      
volumes:
  postgres_data:
  rabbitmq_data:
