services:
  user-service:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - user-db
      - rabbitmq
    environment:
      - DB_HOST=db
      - DB_NAME=user_service_db
      - DB_USER=user_service_user
      - DB_PASSWORD=user_service_password
  user-db:
    image: postgres:14
    environment:
      - POSTGRES_DB=user_service_db
      - POSTGRES_USER=user_service_user
      - POSTGRES_PASSWORD=user_service_password

  rabbitmq:
    image: rabbitmq:3
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


  celery:
    build: .
    command: celery -A user_service beat --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - user-service
      - rabbitmq
    environment:
      - DB_HOST=db
      - DB_NAME=user_service_db
      - DB_USER=user_service_user
      - DB_PASSWORD=user_service_password
      
volumes:
  postgres_data:
  rabbitmq_data:
